name = "CarlemanLinearization"
uuid = "4803f6b2-022a-4c1b-a771-522a3413ec86"
version = "0.3.1"

[deps]
IntervalArithmetic = "d1acc4aa-44c8-5952-acd4-ba5d80a2a253"
IterTools = "c8e1da08-722c-5040-9ed9-7db0dc04731e"
LazySets = "b4f0291d-fe17-52bc-9479-3d1a343d9043"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MultivariatePolynomials = "102ac46a-7ee4-5c85-9060-abc95bfdeaa3"
ReachabilityAnalysis = "1e97bd63-91d1-579d-8e8d-501d2b57c93f"
Requires = "ae029012-a4dd-5104-9daa-d747884805df"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[compat]
DynamicPolynomials = "0.3, 0.4"
MultivariatePolynomials = "0.3, 0.4"
julia = "1"

[extras]
DynamicPolynomials = "7c1d4256-1411-5781-91ec-d7bc3513ac07"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["DynamicPolynomials", "Test"]
